"""empty message

Revision ID: 08625bb59a3c
Revises: 8fab3a911613
Create Date: 2021-03-19 15:48:48.697235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08625bb59a3c'
down_revision = '8fab3a911613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
