"""empty message

Revision ID: 951fb00fd6bf
Revises: fc66c95c8915
Create Date: 2021-03-17 18:50:24.667737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951fb00fd6bf'
down_revision = 'fc66c95c8915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
